import type { Metadata } from "next";
import React from "react";
<<<<<<< feature/application-form
import { Geist, Geist_Mono } from "next/font/google";
=======
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { Archivo_Black } from "next/font/google";
>>>>>>> develop
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-sans",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const archivoBlack = Archivo_Black({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-archivo-black",
});

export const metadata: Metadata = {
  title: "elbnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
<<<<<<< feature/application-form
    <html lang="en" className={cn("font-sans", geist.variable)}>
=======
    <html lang="en" className={cn("font-sans", inter.variable, archivoBlack.variable)}>
>>>>>>> develop
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          "antialiased"
        )}
      >
        <TooltipProvider>
          {children}
        </TooltipProvider>
      </body>
    </html>
  );
}