name: Main branch protection

on:
  pull_request:
    branches: [ main ]
  
jobs:
  branch-check:
      runs-on: ubuntu-latest
      steps:
        - name: Check source branch
          run: |
            echo "🔍 Checking source branch: ${GITHUB_HEAD_REF}"
            if [[ "${GITHUB_HEAD_REF}" != "develop" ]]; then
              echo "❌ Error: Pull request must come from 'develop' branch"
              exit 1
            fi